// pays.js - Liste complète des pays (bilingue FR/EN)
window.YOTEACHER_COUNTRIES = [
    {code: "AF", name_fr: "Afghanistan", name_en: "Afghanistan"},
    {code: "ZA", name_fr: "Afrique du Sud", name_en: "South Africa"},
    {code: "AL", name_fr: "Albanie", name_en: "Albania"},
    {code: "DZ", name_fr: "Algérie", name_en: "Algeria"},
    {code: "DE", name_fr: "Allemagne", name_en: "Germany"},
    {code: "AD", name_fr: "Andorre", name_en: "Andorra"},
    {code: "AO", name_fr: "Angola", name_en: "Angola"},
    {code: "AI", name_fr: "Anguilla", name_en: "Anguilla"},
    {code: "AQ", name_fr: "Antarctique", name_en: "Antarctica"},
    {code: "AG", name_fr: "Antigua-et-Barbuda", name_en: "Antigua and Barbuda"},
    {code: "SA", name_fr: "Arabie saoudite", name_en: "Saudi Arabia"},
    {code: "AR", name_fr: "Argentine", name_en: "Argentina"},
    {code: "AM", name_fr: "Arménie", name_en: "Armenia"},
    {code: "AW", name_fr: "Aruba", name_en: "Aruba"},
    {code: "AU", name_fr: "Australie", name_en: "Australia"},
    {code: "AT", name_fr: "Autriche", name_en: "Austria"},
    {code: "AZ", name_fr: "Azerbaïdjan", name_en: "Azerbaijan"},
    {code: "BS", name_fr: "Bahamas", name_en: "Bahamas"},
    {code: "BH", name_fr: "Bahreïn", name_en: "Bahrain"},
    {code: "BD", name_fr: "Bangladesh", name_en: "Bangladesh"},
    {code: "BB", name_fr: "Barbade", name_en: "Barbados"},
    {code: "BE", name_fr: "Belgique", name_en: "Belgium"},
    {code: "BZ", name_fr: "Belize", name_en: "Belize"},
    {code: "BJ", name_fr: "Bénin", name_en: "Benin"},
    {code: "BM", name_fr: "Bermudes", name_en: "Bermuda"},
    {code: "BT", name_fr: "Bhoutan", name_en: "Bhutan"},
    {code: "BY", name_fr: "Biélorussie", name_en: "Belarus"},
    {code: "BO", name_fr: "Bolivie", name_en: "Bolivia, Plurinational State of"},
    {code: "BA", name_fr: "Bosnie-Herzégovine", name_en: "Bosnia and Herzegovina"},
    {code: "BW", name_fr: "Botswana", name_en: "Botswana"},
    {code: "BR", name_fr: "Brésil", name_en: "Brazil"},
    {code: "BN", name_fr: "Brunei", name_en: "Brunei Darussalam"},
    {code: "BG", name_fr: "Bulgarie", name_en: "Bulgaria"},
    {code: "BF", name_fr: "Burkina Faso", name_en: "Burkina Faso"},
    {code: "BI", name_fr: "Burundi", name_en: "Burundi"},
    {code: "KH", name_fr: "Cambodge", name_en: "Cambodia"},
    {code: "CM", name_fr: "Cameroun", name_en: "Cameroon"},
    {code: "CA", name_fr: "Canada", name_en: "Canada"},
    {code: "CV", name_fr: "Cap-Vert", name_en: "Cabo Verde"},
    {code: "CL", name_fr: "Chili", name_en: "Chile"},
    {code: "CN", name_fr: "Chine", name_en: "China"},
    {code: "CY", name_fr: "Chypre", name_en: "Cyprus"},
    {code: "CO", name_fr: "Colombie", name_en: "Colombia"},
    {code: "KM", name_fr: "Comores", name_en: "Comoros"},
    {code: "CG", name_fr: "Congo-Brazzaville", name_en: "Congo"},
    {code: "CD", name_fr: "Congo-Kinshasa", name_en: "Congo, Democratic Republic of the"},
    {code: "KP", name_fr: "Corée du Nord", name_en: "Korea, Democratic People\'s Republic of"},
    {code: "KR", name_fr: "Corée du Sud", name_en: "Korea, Republic of"},
    {code: "CR", name_fr: "Costa Rica", name_en: "Costa Rica"},
    {code: "CI", name_fr: "Côte d\'Ivoire", name_en: "Côte d\'Ivoire"},
    {code: "HR", name_fr: "Croatie", name_en: "Croatia"},
    {code: "CU", name_fr: "Cuba", name_en: "Cuba"},
    {code: "DK", name_fr: "Danemark", name_en: "Denmark"},
    {code: "DJ", name_fr: "Djibouti", name_en: "Djibouti"},
    {code: "DM", name_fr: "Dominique", name_en: "Dominica"},
    {code: "EG", name_fr: "Égypte", name_en: "Egypt"},
    {code: "AE", name_fr: "Émirats arabes unis", name_en: "United Arab Emirates"},
    {code: "EC", name_fr: "Équateur", name_en: "Ecuador"},
    {code: "ER", name_fr: "Érythrée", name_en: "Eritrea"},
    {code: "ES", name_fr: "Espagne", name_en: "Spain"},
    {code: "EE", name_fr: "Estonie", name_en: "Estonia"},
    {code: "SZ", name_fr: "Eswatini", name_en: "Eswatini"},
    {code: "VA", name_fr: "État de la Cité du Vatican", name_en: "Holy See"},
    {code: "FM", name_fr: "États fédérés de Micronésie", name_en: "Micronesia, Federated States of"},
    {code: "US", name_fr: "États-Unis", name_en: "United States of America"},
    {code: "ET", name_fr: "Éthiopie", name_en: "Ethiopia"},
    {code: "FJ", name_fr: "Fidji", name_en: "Fiji"},
    {code: "FI", name_fr: "Finlande", name_en: "Finland"},
    {code: "FR", name_fr: "France", name_en: "France"},
    {code: "GA", name_fr: "Gabon", name_en: "Gabon"},
    {code: "GM", name_fr: "Gambie", name_en: "Gambia"},
    {code: "GE", name_fr: "Géorgie", name_en: "Georgia"},
    {code: "GH", name_fr: "Ghana", name_en: "Ghana"},
    {code: "GI", name_fr: "Gibraltar", name_en: "Gibraltar"},
    {code: "GR", name_fr: "Grèce", name_en: "Greece"},
    {code: "GD", name_fr: "Grenade", name_en: "Grenada"},
    {code: "GL", name_fr: "Groenland", name_en: "Greenland"},
    {code: "GP", name_fr: "Guadeloupe", name_en: "Guadeloupe"},
    {code: "GU", name_fr: "Guam", name_en: "Guam"},
    {code: "GT", name_fr: "Guatemala", name_en: "Guatemala"},
    {code: "GG", name_fr: "Guernesey", name_en: "Guernsey"},
    {code: "GN", name_fr: "Guinée", name_en: "Guinea"},
    {code: "GQ", name_fr: "Guinée équatoriale", name_en: "Equatorial Guinea"},
    {code: "GW", name_fr: "Guinée-Bissau", name_en: "Guinea-Bissau"},
    {code: "GY", name_fr: "Guyana", name_en: "Guyana"},
    {code: "GF", name_fr: "Guyane française", name_en: "French Guiana"},
    {code: "HT", name_fr: "Haïti", name_en: "Haiti"},
    {code: "HN", name_fr: "Honduras", name_en: "Honduras"},
    {code: "HU", name_fr: "Hongrie", name_en: "Hungary"},
    {code: "BV", name_fr: "Île Bouvet", name_en: "Bouvet Island"},
    {code: "CX", name_fr: "Île Christmas", name_en: "Christmas Island"},
    {code: "IM", name_fr: "Île de Man", name_en: "Isle of Man"},
    {code: "NF", name_fr: "Île Norfolk", name_en: "Norfolk Island"},
    {code: "AX", name_fr: "Îles Åland", name_en: "Åland Islands"},
    {code: "KY", name_fr: "Îles Caïmans", name_en: "Cayman Islands"},
    {code: "CC", name_fr: "Îles Cocos", name_en: "Cocos (Keeling) Islands"},
    {code: "CK", name_fr: "Îles Cook", name_en: "Cook Islands"},
    {code: "FO", name_fr: "Îles Féroé", name_en: "Faroe Islands"},
    {code: "HM", name_fr: "Îles Heard-et-MacDonald", name_en: "Heard Island and McDonald Islands"},
    {code: "FK", name_fr: "Îles Malouines", name_en: "Falkland Islands (Malvinas)"},
    {code: "MP", name_fr: "Îles Mariannes du Nord", name_en: "Northern Mariana Islands"},
    {code: "MH", name_fr: "Îles Marshall", name_en: "Marshall Islands"},
    {code: "UM", name_fr: "Îles mineures éloignées des États-Unis", name_en: "United States Minor Outlying Islands"},
    {code: "PN", name_fr: "Îles Pitcairn", name_en: "Pitcairn"},
    {code: "SB", name_fr: "Îles Salomon", name_en: "Solomon Islands"},
    {code: "TC", name_fr: "Îles Turques-et-Caïques", name_en: "Turks and Caicos Islands"},
    {code: "VG", name_fr: "Îles Vierges britanniques", name_en: "Virgin Islands (British)"},
    {code: "VI", name_fr: "Îles Vierges des États-Unis", name_en: "Virgin Islands (U.S.)"},
    {code: "IN", name_fr: "Inde", name_en: "India"},
    {code: "ID", name_fr: "Indonésie", name_en: "Indonesia"},
    {code: "IQ", name_fr: "Irak", name_en: "Iraq"},
    {code: "IR", name_fr: "Iran", name_en: "Iran, Islamic Republic of"},
    {code: "IE", name_fr: "Irlande", name_en: "Ireland"},
    {code: "IS", name_fr: "Islande", name_en: "Iceland"},
    {code: "IL", name_fr: "Israël", name_en: "Israel"},
    {code: "IT", name_fr: "Italie", name_en: "Italy"},
    {code: "JM", name_fr: "Jamaïque", name_en: "Jamaica"},
    {code: "JP", name_fr: "Japon", name_en: "Japan"},
    {code: "JE", name_fr: "Jersey", name_en: "Jersey"},
    {code: "JO", name_fr: "Jordanie", name_en: "Jordan"},
    {code: "KZ", name_fr: "Kazakhstan", name_en: "Kazakhstan"},
    {code: "KE", name_fr: "Kenya", name_en: "Kenya"},
    {code: "KG", name_fr: "Kirghizistan", name_en: "Kyrgyzstan"},
    {code: "KI", name_fr: "Kiribati", name_en: "Kiribati"},
    {code: "KW", name_fr: "Koweït", name_en: "Kuwait"},
    {code: "RE", name_fr: "La Réunion", name_en: "Réunion"},
    {code: "LA", name_fr: "Laos", name_en: "Lao People\'s Democratic Republic"},
    {code: "LS", name_fr: "Lesotho", name_en: "Lesotho"},
    {code: "LV", name_fr: "Lettonie", name_en: "Latvia"},
    {code: "LB", name_fr: "Liban", name_en: "Lebanon"},
    {code: "LR", name_fr: "Liberia", name_en: "Liberia"},
    {code: "LY", name_fr: "Libye", name_en: "Libya"},
    {code: "LI", name_fr: "Liechtenstein", name_en: "Liechtenstein"},
    {code: "LT", name_fr: "Lituanie", name_en: "Lithuania"},
    {code: "LU", name_fr: "Luxembourg", name_en: "Luxembourg"},
    {code: "MK", name_fr: "Macédoine du Nord", name_en: "North Macedonia"},
    {code: "MG", name_fr: "Madagascar", name_en: "Madagascar"},
    {code: "MY", name_fr: "Malaisie", name_en: "Malaysia"},
    {code: "MW", name_fr: "Malawi", name_en: "Malawi"},
    {code: "MV", name_fr: "Maldives", name_en: "Maldives"},
    {code: "ML", name_fr: "Mali", name_en: "Mali"},
    {code: "MT", name_fr: "Malte", name_en: "Malta"},
    {code: "MA", name_fr: "Maroc", name_en: "Morocco"},
    {code: "MQ", name_fr: "Martinique", name_en: "Martinique"},
    {code: "MU", name_fr: "Maurice", name_en: "Mauritius"},
    {code: "MR", name_fr: "Mauritanie", name_en: "Mauritania"},
    {code: "YT", name_fr: "Mayotte", name_en: "Mayotte"},
    {code: "MX", name_fr: "Mexique", name_en: "Mexico"},
    {code: "MD", name_fr: "Moldavie", name_en: "Moldova, Republic of"},
    {code: "MC", name_fr: "Monaco", name_en: "Monaco"},
    {code: "MN", name_fr: "Mongolie", name_en: "Mongolia"},
    {code: "ME", name_fr: "Monténégro", name_en: "Montenegro"},
    {code: "MS", name_fr: "Montserrat", name_en: "Montserrat"},
    {code: "MZ", name_fr: "Mozambique", name_en: "Mozambique"},
    {code: "MM", name_fr: "Myanmar", name_en: "Myanmar"},
    {code: "NA", name_fr: "Namibie", name_en: "Namibia"},
    {code: "NR", name_fr: "Nauru", name_en: "Nauru"},
    {code: "NP", name_fr: "Népal", name_en: "Nepal"},
    {code: "NI", name_fr: "Nicaragua", name_en: "Nicaragua"},
    {code: "NE", name_fr: "Niger", name_en: "Niger"},
    {code: "NG", name_fr: "Nigeria", name_en: "Nigeria"},
    {code: "NU", name_fr: "Niue", name_en: "Niue"},
    {code: "NO", name_fr: "Norvège", name_en: "Norway"},
    {code: "NC", name_fr: "Nouvelle-Calédonie", name_en: "New Caledonia"},
    {code: "NZ", name_fr: "Nouvelle-Zélande", name_en: "New Zealand"},
    {code: "OM", name_fr: "Oman", name_en: "Oman"},
    {code: "UG", name_fr: "Ouganda", name_en: "Uganda"},
    {code: "UZ", name_fr: "Ouzbékistan", name_en: "Uzbekistan"},
    {code: "PK", name_fr: "Pakistan", name_en: "Pakistan"},
    {code: "PW", name_fr: "Palaos", name_en: "Palau"},
    {code: "PA", name_fr: "Panama", name_en: "Panama"},
    {code: "PG", name_fr: "Papouasie-Nouvelle-Guinée", name_en: "Papua New Guinea"},
    {code: "PY", name_fr: "Paraguay", name_en: "Paraguay"},
    {code: "NL", name_fr: "Pays-Bas", name_en: "Netherlands"},
    {code: "BQ", name_fr: "Pays-Bas caribéens", name_en: "Bonaire, Sint Eustatius and Saba"},
    {code: "PE", name_fr: "Pérou", name_en: "Peru"},
    {code: "PH", name_fr: "Philippines", name_en: "Philippines"},
    {code: "PL", name_fr: "Pologne", name_en: "Poland"},
    {code: "PF", name_fr: "Polynésie française", name_en: "French Polynesia"},
    {code: "PR", name_fr: "Porto Rico", name_en: "Puerto Rico"},
    {code: "PT", name_fr: "Portugal", name_en: "Portugal"},
    {code: "QA", name_fr: "Qatar", name_en: "Qatar"},
    {code: "HK", name_fr: "R.A.S. chinoise de Hong Kong", name_en: "Hong Kong"},
    {code: "MO", name_fr: "R.A.S. chinoise de Macao", name_en: "Macao"},
    {code: "CF", name_fr: "République centrafricaine", name_en: "Central African Republic"},
    {code: "DO", name_fr: "République dominicaine", name_en: "Dominican Republic"},
    {code: "RO", name_fr: "Roumanie", name_en: "Romania"},
    {code: "GB", name_fr: "Royaume-Uni", name_en: "United Kingdom of Great Britain and Northern Ireland"},
    {code: "RU", name_fr: "Russie", name_en: "Russian Federation"},
    {code: "RW", name_fr: "Rwanda", name_en: "Rwanda"},
    {code: "EH", name_fr: "Sahara occidental", name_en: "Western Sahara"},
    {code: "BL", name_fr: "Saint-Barthélemy", name_en: "Saint Barthélemy"},
    {code: "KN", name_fr: "Saint-Christophe-et-Niévès", name_en: "Saint Kitts and Nevis"},
    {code: "SM", name_fr: "Saint-Marin", name_en: "San Marino"},
    {code: "MF", name_fr: "Saint-Martin", name_en: "Saint Martin (French part)"},
    {code: "SX", name_fr: "Saint-Martin (partie néerlandaise)", name_en: "Sint Maarten (Dutch part)"},
    {code: "PM", name_fr: "Saint-Pierre-et-Miquelon", name_en: "Saint Pierre and Miquelon"},
    {code: "VC", name_fr: "Saint-Vincent-et-les-Grenadines", name_en: "Saint Vincent and the Grenadines"},
    {code: "SH", name_fr: "Sainte-Hélène", name_en: "Saint Helena, Ascension and Tristan da Cunha"},
    {code: "LC", name_fr: "Sainte-Lucie", name_en: "Saint Lucia"},
    {code: "SV", name_fr: "Salvador", name_en: "El Salvador"},
    {code: "WS", name_fr: "Samoa", name_en: "Samoa"},
    {code: "AS", name_fr: "Samoa américaines", name_en: "American Samoa"},
    {code: "ST", name_fr: "Sao Tomé-et-Principe", name_en: "Sao Tome and Principe"},
    {code: "SN", name_fr: "Sénégal", name_en: "Senegal"},
    {code: "RS", name_fr: "Serbie", name_en: "Serbia"},
    {code: "SC", name_fr: "Seychelles", name_en: "Seychelles"},
    {code: "SL", name_fr: "Sierra Leone", name_en: "Sierra Leone"},
    {code: "SG", name_fr: "Singapour", name_en: "Singapore"},
    {code: "SK", name_fr: "Slovaquie", name_en: "Slovakia"},
    {code: "SI", name_fr: "Slovénie", name_en: "Slovenia"},
    {code: "SO", name_fr: "Somalie", name_en: "Somalia"},
    {code: "SD", name_fr: "Soudan", name_en: "Sudan"},
    {code: "SS", name_fr: "Soudan du Sud", name_en: "South Sudan"},
    {code: "LK", name_fr: "Sri Lanka", name_en: "Sri Lanka"},
    {code: "SE", name_fr: "Suède", name_en: "Sweden"},
    {code: "CH", name_fr: "Suisse", name_en: "Switzerland"},
    {code: "SR", name_fr: "Suriname", name_en: "Suriname"},
    {code: "SJ", name_fr: "Svalbard et île Jan Mayen", name_en: "Svalbard and Jan Mayen"},
    {code: "SY", name_fr: "Syrie", name_en: "Syrian Arab Republic"},
    {code: "TJ", name_fr: "Tadjikistan", name_en: "Tajikistan"},
    {code: "TW", name_fr: "Taïwan", name_en: "Taiwan, Province of China"},
    {code: "TZ", name_fr: "Tanzanie", name_en: "Tanzania, United Republic of"},
    {code: "TD", name_fr: "Tchad", name_en: "Chad"},
    {code: "CZ", name_fr: "Tchéquie", name_en: "Czechia"},
    {code: "TF", name_fr: "Terres australes françaises", name_en: "French Southern Territories"},
    {code: "IO", name_fr: "Territoire britannique de l\'océan Indien", name_en: "British Indian Ocean Territory"},
    {code: "PS", name_fr: "Territoires palestiniens", name_en: "Palestine, State of"},
    {code: "TH", name_fr: "Thaïlande", name_en: "Thailand"},
    {code: "TL", name_fr: "Timor oriental", name_en: "Timor-Leste"},
    {code: "TG", name_fr: "Togo", name_en: "Togo"},
    {code: "TK", name_fr: "Tokelau", name_en: "Tokelau"},
    {code: "TO", name_fr: "Tonga", name_en: "Tonga"},
    {code: "TT", name_fr: "Trinité-et-Tobago", name_en: "Trinidad and Tobago"},
    {code: "TN", name_fr: "Tunisie", name_en: "Tunisia"},
    {code: "TM", name_fr: "Turkménistan", name_en: "Turkmenistan"},
    {code: "TR", name_fr: "Turquie", name_en: "Türkiye"},
    {code: "TV", name_fr: "Tuvalu", name_en: "Tuvalu"},
    {code: "UA", name_fr: "Ukraine", name_en: "Ukraine"},
    {code: "UY", name_fr: "Uruguay", name_en: "Uruguay"},
    {code: "VU", name_fr: "Vanuatu", name_en: "Vanuatu"},
    {code: "VE", name_fr: "Venezuela", name_en: "Venezuela, Bolivarian Republic of"},
    {code: "VN", name_fr: "Vietnam", name_en: "Viet Nam"},
    {code: "WF", name_fr: "Wallis-et-Futuna", name_en: "Wallis and Futuna"},
    {code: "YE", name_fr: "Yémen", name_en: "Yemen"},
    {code: "ZM", name_fr: "Zambie", name_en: "Zambia"},
    {code: "ZW", name_fr: "Zimbabwe", name_en: "Zimbabwe"},
];

// Fonction pour charger les pays dans un select
window.loadCountriesIntoSelect = function(selectId, selectedCountry) {
    selectedCountry = selectedCountry || '';

    var select = document.getElementById(selectId);
    if (!select) return;

    // Sauvegarder la sélection actuelle
    var currentValue = selectedCountry || select.value;

    // Vider le select (garder la première option si elle existe)
    var firstOption = select.options[0];
    select.innerHTML = '';
    if (firstOption) {
        select.appendChild(firstOption);
    }

    // Détecter la langue courante
    var lang = 'fr';
    if (window.translationManager && typeof window.translationManager.getCurrentLanguage === 'function') {
        lang = window.translationManager.getCurrentLanguage();
    } else {
        lang = localStorage.getItem('language') || navigator.language.split('-')[0] || 'fr';
    }

    // Trier les pays par nom dans la langue courante
    var countries = [...window.YOTEACHER_COUNTRIES].sort(function(a, b) {
        var nameA = (lang === 'en' ? a.name_en : a.name_fr);
        var nameB = (lang === 'en' ? b.name_en : b.name_fr);
        return nameA.localeCompare(nameB, lang === 'en' ? 'en' : 'fr');
    });

    // Ajouter les pays
    countries.forEach(function(country) {
        var option = document.createElement('option');
        option.value = country.code;
        option.textContent = (lang === 'en' ? country.name_en : country.name_fr);
        select.appendChild(option);
    });

    // Restaurer la sélection
    if (currentValue) {
        select.value = currentValue;
    }
};

console.log('✅ Liste des pays chargée (' + window.YOTEACHER_COUNTRIES.length + ' pays)');